// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX6ov49bMJr3DBJ3fsKnVhwx1MChh2LPI',
    appId: '1:675100913771:web:7bd31429472454a27b012e',
    messagingSenderId: '675100913771',
    projectId: 'examplify-30df4',
    authDomain: 'examplify-30df4.firebaseapp.com',
    storageBucket: 'examplify-30df4.firebasestorage.app',
    measurementId: 'G-ETPL6BBL0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8G_pWg23d7sMpwDtQuDOmMoEJaHKY2I',
    appId: '1:675100913771:android:28b27bc6ea91a95e7b012e',
    messagingSenderId: '675100913771',
    projectId: 'examplify-30df4',
    storageBucket: 'examplify-30df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2ZrROGOPERfNu2rZafKQ5EahuawqBic',
    appId: '1:675100913771:ios:cf6543a5b7682f727b012e',
    messagingSenderId: '675100913771',
    projectId: 'examplify-30df4',
    storageBucket: 'examplify-30df4.firebasestorage.app',
    iosBundleId: 'com.example.examplify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa2ZrROGOPERfNu2rZafKQ5EahuawqBic',
    appId: '1:675100913771:ios:cf6543a5b7682f727b012e',
    messagingSenderId: '675100913771',
    projectId: 'examplify-30df4',
    storageBucket: 'examplify-30df4.firebasestorage.app',
    iosBundleId: 'com.example.examplify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX6ov49bMJr3DBJ3fsKnVhwx1MChh2LPI',
    appId: '1:675100913771:web:c0195d0cfe9c68797b012e',
    messagingSenderId: '675100913771',
    projectId: 'examplify-30df4',
    authDomain: 'examplify-30df4.firebaseapp.com',
    storageBucket: 'examplify-30df4.firebasestorage.app',
    measurementId: 'G-FXJH21XZ2N',
  );
}
